version: '3'
services:
  web:
    build: ./app
    ports:
      - "9000:80"
    restart: unless-stopped
  rails:
    build: ./rails
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./rails:/app
      - /app/tmp
      - /app/node_modules
    environment:
      RAILS_ENV:
      SECRET_KEY_BASE:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    restart: unless-stopped
  db:
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD:
    restart: unless-stopped
