version: '3'
services:
  web:
    build: ./app
    ports:
      - "9000:80"
    restart: unless-stopped
  rails:
    build: ./rails
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/tmp
      - /app/node_modules
    environment:
      RAILS_ENV: development
  db:
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgresql/data
