version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
  web:
    build: ./app
    ports:
      - "8000:3000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      RAILS_ENV: development
      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_LOG_TO_STDOUT: 'true'
    depends_on:
      - db
    restart: unless-stopped
  rails:
    build: ./rails
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./rails:/app
      - /app/tmp
      - /app/node_modules
    environment:
      RAILS_ENV: development
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
  db:
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: supersecret
