version: '3'
services:
  go:
    build: ./go
    ports:
      - "9001:8080"
    restart: unless-stopped

  rails:
    build: ./rails
    depends_on:
      - db
    ports:
      - "9000:3000"
    volumes:
      - ./rails:/app
      - dashboard-rails-node-modules:/app/node_modules
    tmpfs:
      - /app/tmp
    environment:
      RAILS_ENV:
      SECRET_KEY_BASE:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      WEATHER_API_KEY:
      WEATHER_API_LAT:
      WEATHER_API_LON:
    restart: unless-stopped

  db:
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD:
    restart: unless-stopped

volumes:
  dashboard-rails-node-modules:
