---
- hosts: all
  vars:
    dashboard_directory: /home/pi/leo-dashboard-v2
    git_repo: git@github.com:dandezille/leo-dashboard.git
    git_branch: dev/docker
  tasks:
    - name: Get latest dashboard code
      git:
        repo: "{{git_repo}}"
        dest: "{{dashboard_directory}}"
        version: "{{git_branch}}"
        force: yes
        accept_hostkey: yes
      register: checkout
      notify: refresh browser

    - name: Start with docker compose
      docker_compose:
        project_src: "{{dashboard_directory}}"
        build: yes
      register: docker_compose_out
      vars:
        ansible_python_interpreter: /usr/bin/python3

    - debug:
        var: docker_compose_out

  handlers:
    - name: restart service
      become: yes
      systemd:
        state: restarted
        name: "{{service_name}}"
        enabled: yes
        daemon_reload: yes
      notify: refresh browser

    - name: refresh browser
      command: xdotool getactivewindow key F5
      environment:
        DISPLAY: ":0"
