---
- hosts: all
  vars:
    dashboard_directory: /home/pi/leo-dashboard-rails
    git_repo: git@github.com:dandezille/leo-dashboard.git
    git_branch: dev/server
  tasks:
    - name: Get latest dashboard code
      git:
        repo: "{{git_repo}}"
        dest: "{{dashboard_directory}}"
        version: "{{git_branch}}"
        force: yes
        accept_hostkey: yes

    - name: Start with docker compose
      docker_compose:
        project_src: "{{dashboard_directory}}"
        build: yes
        remove_orphans: yes
      vars:
        ansible_python_interpreter: /usr/bin/python3
      notify: refresh browser

  handlers:
    - name: refresh browser
      command: xdotool getactivewindow key F5
      environment:
        DISPLAY: ":0"
