---
- hosts: all
  vars:
    dashboard_directory: /home/pi/leo-dashboard
  tasks:
    - include: tasks/leo-dashboard.yml
  handlers:
    - name: reboot
      command: xdotool getactivewindow key F5
      environment:
        DISPLAY: ":0"
