---
- hosts: all
  environment:
    COMPOSE_HTTP_TIMEOUT: 240
  tasks:
    - include: tasks/dashboard-source.yml
    - include: tasks/electron-build.yml
    - include: tasks/dashboard-build.yml
  handlers:
    - name: refresh browser
      command: xdotool getactivewindow key F5
      environment:
        DISPLAY: ":0"

    - name: reboot
      become: yes
      reboot:
