---
- hosts: all
  vars:
    dashboard_directory: /home/pi/leo-dashboard
    git_repo: git@github.com:dandezille/leo-dashboard.git
    git_branch: dev/server
  tasks:
    - name: Get latest dashboard code
      git:
        repo: "{{git_repo}}"
        dest: "{{dashboard_directory}}"
        version: "{{git_branch}}"
        force: yes
        accept_hostkey: yes
      register: checkout
      notify: refresh browser

    - name: Start docker-compose
      docker_compose:
        build: yes
        state: present
        project_src: leo-dashboard

    - meta: end_play

    - name: Install service unit file
      become: yes
      template: 
        src: dashboard-app.service.j2 
        dest: /etc/systemd/system/dashboard-app.service
      notify: restart service

  handlers:
    - name: restart service
      become: yes
      systemd:
        state: restarted
        name: dashboard-app.service
        enabled: yes
        daemon_reload: yes
      notify: refresh browser

    - name: refresh browser
      command: xdotool getactivewindow key F5
      environment:
        DISPLAY: ":0"
