---
- hosts: all
  vars:
    dashboard_directory: /home/pi/leo-dashboard
  environment: 
    COMPOSE_HTTP_TIMEOUT: 120
  tasks:
    - name: Get latest dashboard code
      git:
        repo: git@github.com:dandezille/leo-dashboard.git
        dest: "{{dashboard_directory}}"
        version: master
        force: yes
        accept_hostkey: yes

    - name: Start with docker compose
      docker_compose:
        project_src: "{{dashboard_directory}}"
        build: yes
        remove_orphans: yes
      vars:
        ansible_python_interpreter: /usr/bin/python3
      notify: refresh browser

    - name: Clean up docker resources
      docker_prune:
        containers: yes
        images: yes
        images_filters:
          dangling: false
        networks: yes
        volumes: yes
        builder_cache: yes
      register: docker_prune_out

    - debug:
        var: docker_prune_out

  handlers:
    - name: refresh browser
      command: xdotool getactivewindow key F5
      environment:
        DISPLAY: ":0"
