---
- hosts: all
  environment:
    COMPOSE_HTTP_TIMEOUT: 240
  tasks:
    - include: tasks/dashboard.yml
  handlers:
    - name: refresh browser
      command: xdotool getactivewindow key F5
      environment:
        DISPLAY: ":0"
