---
- name: Install X server, window manager, Chromium and required tools
  become: yes
  apt:
    install_recommends: no
    pkg:
      - xserver-xorg
      - x11-xserver-utils
      - xdotool
      - lightdm
      - openbox
      - fonts-noto-color-emoji
      - unclutter
      - build-essential
      - sed
      - git
      - neovim
      - realvnc-vnc-server 
      - realvnc-vnc-viewer
      - tmux
