---
- name: Build electron app
  shell: ../bin/build-electron
  register: electron_build
  delegate_to: 127.0.0.1

- debug: var=electron_build.stdout

- name: Copy electron app
  copy:
    src: ../electron
    dest: "{{deploy_directory}}/electron"
  register: electron_copy

- debug: var=electron_copy.stdout
