---
- name: Add NodeSource signing key
  become: yes
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add NodeSource repo
  become: yes
  apt_repository:
    repo: deb https://deb.nodesource.com/node_12.x {{ansible_distribution_release}} main
    state: present
