---
- name: Openbox Configuration
  become: yes
  blockinfile:
    path: /etc/xdg/openbox/autostart
    block: |
      # Disable any form of screen saver / screen blanking / power management
      xset s off
      xset s noblank
      xset -dpms

      # Hide cursor after 0.5s
      unclutter -idle 0.5 -root &

      # Wait for server to be up
      while curl localhost:9000 -gt 0
      do
        sleep 5
        echo "Trying again..."
        curl $1
      done

      # Start Chromium in kiosk mode
      sed -i 's/"exited_cleanly":false/"exited_cleanly":true/' ~/.config/chromium/'Local State'
      sed -i 's/"exited_cleanly":false/"exited_cleanly":true/; s/"exit_type":"[^"]\+"/"exit_type":"Normal"/' ~/.config/chromium/Default/Preferences
      chromium-browser --noerrdialogs --disable-infobars --kiosk  --incognito 'http://localhost:9000'
  notify: reboot
