---
- name: Add Yarn signing key
  become: yes
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: Add Yarn repo
  become: yes
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present
