---
- hosts: all
  tasks:
    - name: Install git
      become: yes
      apt:
        name: git
        state: present

    - name: Get latest dashboard code
      git:
        repo: git@github.com:dandezille/leo-dashboard.git
        dest: ~/leo-dashboard
        accept_hostkey: yes
