---
- hosts: all
  tasks:
    - name: Configure screen rotation
      become: yes
      lineinfile:
        path: /boot/config.txt
        regexp: "^lcd_rotate="
        line: lcd_rotate=2
      notify: reboot

    - name: Generate ssh keypair
      openssh_keypair:
        path: ~/.ssh/id_rsa
      register: ssh_keypair

    - name: Print ssh public key
      debug:
        var: ssh_keypair.public_key

    - name: Upgrade all packages to latest version
      become: yes
      apt:
        update_cache: yes
        upgrade: "yes"
      notify: reboot

    - name: Install X server, window manager, Chromium and required tools
      become: yes
      apt:
        install_recommends: no
        pkg:
          - xserver-xorg
          - x11-xserver-utils
          - lightdm
          - openbox
          - chromium-browser
          - unclutter
          - sed
          - git
          - python3
      notify: reboot

    - name: Clean up apt packages
      become: yes
      apt:
        autoclean: yes
        autoremove: yes
      notify: reboot

    - name: Openbox Configuration
      become: yes
      blockinfile:
        path: /etc/xdg/openbox/autostart
        block: |
          # Disable any form of screen saver / screen blanking / power management
          xset s off
          xset s noblank
          xset -dpms

          # Hide cursor after 0.5s
          unclutter -idle 0.5 -root &

          # Start Chromium in kiosk mode
          sed -i 's/"exited_cleanly":false/"exited_cleanly":true/' ~/.config/chromium/'Local State'
          sed -i 's/"exited_cleanly":false/"exited_cleanly":true/; s/"exit_type":"[^"]\+"/"exit_type":"Normal"/' ~/.config/chromium/Default/Preferences
          chromium-browser --noerrdialogs --disable-infobars --kiosk 'https://google.com'
      notify: reboot

  handlers:
    - name: reboot
      become: yes
      reboot: