---
- hosts: all
  tasks:
    - name: Configure screen rotation
      become: yes
      lineinfile:
        path: /boot/config.txt
        regexp: "^lcd_rotate="
        line: lcd_rotate=2
      notify: reboot

    - name: Generate ssh keypair
      openssh_keypair:
        path: ~/.ssh/id_rsa
      register: ssh_keypair

    - name: Print ssh public key
      debug:
        var: ssh_keypair.public_key

    - name: Add NodeSource signing key
      become: yes
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add NodeSource repo
      become: yes
      apt_repository:
        repo: deb https://deb.nodesource.com/node_12.x {{ansible_distribution_release}} main
        state: present

    - name: Add Yarn signing key
      become: yes
      apt_key:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
        state: present

    - name: Add Yarn repo
      become: yes
      apt_repository:
        repo: deb https://dl.yarnpkg.com/debian/ stable main
        state: present

    - name: Upgrade all packages to latest version
      become: yes
      apt:
        update_cache: yes
        upgrade: "yes"
      notify: reboot

    - name: Install X server, window manager, Chromium and required tools
      become: yes
      apt:
        install_recommends: no
        pkg:
          - xserver-xorg
          - x11-xserver-utils
          - xdotool
          - lightdm
          - openbox
          - chromium-browser
          - fonts-noto-color-emoji
          - unclutter
          - build-essential
          - sed
          - git
          - nodejs
          - neovim
          - nodejs
          - yarn
          - realvnc-vnc-server 
          - realvnc-vnc-viewer
      notify: reboot

    - name: Clean up apt packages
      become: yes
      apt:
        autoclean: yes
        autoremove: yes
      notify: reboot

    - name: Enable vnc server
      become: yes
      command: raspi-config nonint do_vnc 0
      notify: reboot

    - name: Allow non-RealVNC clients
      become: yes
      lineinfile:
        path: /root/.vnc/config.d/vncserver-x11
        regexp: "^Authentication="
        line: Authentication=VncAuth
      notify: reboot

    - name: Set VNC password
      become: yes
      lineinfile:
        path: /root/.vnc/config.d/vncserver-x11
        regexp: "^Password="
        line: Password=23b46a660df761b9
      notify: reboot

    - name: Disable Chromium cache
      become: yes
      lineinfile:
        path: /etc/chromium-browser/default
        regexp: "^CHROMIUM_FLAGS="
        line: CHROMIUM_FLAGS="--disk-cache-dir=/dev/null --disk-cache-size=1"
      notify: reboot

    - name: Openbox Configuration
      become: yes
      blockinfile:
        path: /etc/xdg/openbox/autostart
        block: |
          # Disable any form of screen saver / screen blanking / power management
          xset s off
          xset s noblank
          xset -dpms

          # Hide cursor after 0.5s
          unclutter -idle 0.5 -root &

          # Start Chromium in kiosk mode
          sed -i 's/"exited_cleanly":false/"exited_cleanly":true/' ~/.config/chromium/'Local State'
          sed -i 's/"exited_cleanly":false/"exited_cleanly":true/; s/"exit_type":"[^"]\+"/"exit_type":"Normal"/' ~/.config/chromium/Default/Preferences
          chromium-browser --noerrdialogs --disable-infobars --kiosk  --incognito 'http://localhost:8000'
      notify: reboot

    - name: Create cron job to turn display on
      become: yes
      cron:
        name: Display on
        minute: '0'
        hour: '7'
        job: echo 0 > /sys/class/backlight/rpi_backlight/bl_power

    - name: Create cron job to turn display off
      become: yes
      cron:
        name: Display off
        minute: '0'
        hour: '20'
        job: echo 1 > /sys/class/backlight/rpi_backlight/bl_power

  handlers:
    - name: reboot
      become: yes
      reboot: