name: CI
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose up -d
      - run: docker-compose run web rails db:create
      - run: docker-compose run web rspec
