name: Run tests
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn --cwd app/ install
      - run: yarn --cwd app/ test
